# Generated by Django 5.1.7 on 2025-03-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_leaverequest_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='employee_id',
            field=models.CharField(default='TEMPID', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
