# Generated by Django 5.1.5 on 2025-04-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employeeprofile_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='employee_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
