# Generated by Django 5.1.5 on 2025-04-14 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_employee_remove_employeeprofile_employee_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
